// Generated by gencpp from file sign_slowdown/Drive_command.msg
// DO NOT EDIT!


#ifndef SIGN_SLOWDOWN_MESSAGE_DRIVE_COMMAND_H
#define SIGN_SLOWDOWN_MESSAGE_DRIVE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sign_slowdown
{
template <class ContainerAllocator>
struct Drive_command_
{
  typedef Drive_command_<ContainerAllocator> Type;

  Drive_command_()
    : speed(0.0)
    , angle(0.0)
    , flag(false)  {
    }
  Drive_command_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , angle(0.0)
    , flag(false)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::sign_slowdown::Drive_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sign_slowdown::Drive_command_<ContainerAllocator> const> ConstPtr;

}; // struct Drive_command_

typedef ::sign_slowdown::Drive_command_<std::allocator<void> > Drive_command;

typedef boost::shared_ptr< ::sign_slowdown::Drive_command > Drive_commandPtr;
typedef boost::shared_ptr< ::sign_slowdown::Drive_command const> Drive_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sign_slowdown::Drive_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sign_slowdown::Drive_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sign_slowdown::Drive_command_<ContainerAllocator1> & lhs, const ::sign_slowdown::Drive_command_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.angle == rhs.angle &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sign_slowdown::Drive_command_<ContainerAllocator1> & lhs, const ::sign_slowdown::Drive_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sign_slowdown

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sign_slowdown::Drive_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sign_slowdown::Drive_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sign_slowdown::Drive_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sign_slowdown::Drive_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sign_slowdown::Drive_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sign_slowdown::Drive_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sign_slowdown::Drive_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95ff01497d9197f16d490d6e129fd2cd";
  }

  static const char* value(const ::sign_slowdown::Drive_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95ff01497d9197f1ULL;
  static const uint64_t static_value2 = 0x6d490d6e129fd2cdULL;
};

template<class ContainerAllocator>
struct DataType< ::sign_slowdown::Drive_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sign_slowdown/Drive_command";
  }

  static const char* value(const ::sign_slowdown::Drive_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sign_slowdown::Drive_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n"
"float32 angle\n"
"bool flag\n"
;
  }

  static const char* value(const ::sign_slowdown::Drive_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sign_slowdown::Drive_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.angle);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drive_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sign_slowdown::Drive_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sign_slowdown::Drive_command_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGN_SLOWDOWN_MESSAGE_DRIVE_COMMAND_H
